name: CI/CD
on:
  push:
    paths:
      - src/**
      - features/**
      - stories/**
      - .github/workflows/CICD.yml

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Retrieve dependency cache
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: js-${{ hashFiles('package-lock.json') }}
          restore-keys: js-
      - name: Install missing dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Run tests
        run: npm test

  storybook:
    name: Publish Storybook to Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Retrieve dependency cache
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: js-${{ hashFiles('package-lock.json') }}
          restore-keys: js-
      - name: Install missing dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Publish
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}

  npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: [ tests, storybook ]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
